services:
  ragify:
    build: .
    ports:
      - "7860:7860"
    environment:
      - STREAMLIT_SERVER_PORT=7860
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      - .:/app
    restart: unless-stopped
